version: '3.1'
services:

  phpmyadmin:
    # build: ./phpmyadmin
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - 6080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    networks:
      - laravel-network 

  db:
    # образ для контейнера должен быть создан из ./db/docker-compose
    # build: ./db
    image: mariadb:latest
    restart: always
    container_name: db
    ports:
      - 8080:3306
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    volumes: 
    # сохраняем базу данных на локальном сервере
      - ./databases:/var/lib/mysql
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge
